### ISSUE TITLE
Provide better feedback when Transaction is not fully signed

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1076]
I'm trying to broadcast a transaction but I keep getting this meaningless error in the broadcast callback, for what I think is a perfectly fine transaction. How can I debug this error? Here's the code that gives the error:

```
<html><body>
<script src="bitcore.min.js"></script>
<script src="bitcore-explorers.min.js"></script>
<script>
var bitcore = require('bitcore');
var explorers = require('bitcore-explorers');

var tx = new bitcore.Transaction('0100000004675f813a8a3bdfcfefc76db024b3c31b41fdec0e8c44cdac5d933b067ae3a045000000006a473044022072c9f556d7116157b208c6774f7f2f0698a29c567c1d82ba0e4b27d31af5bc8c022033a340c0f051ca72bd9fbce8b9156d2ef6e280cf05bce5bfe05ce840ebf7f4bf01210364ca17e9a443f775d3a26cd8e4f4873c7186c481fb741ec5e66b1c9b8571b3c8ffffffff185f22601506eda04d65643a94cb0f1d6ff0350a9c75950d1f80f48f157f0eab0000000000ffffffff9a14bd3b132e84408ded7a2a96f1fa76ed3ec03900673b87abe53161aa3cacfa0000000000ffffffff6928d19b1e902207fb4c8707a7af3ad4c97c70f7c4041255a9682427807392e70100000000ffffffff0280969800000000001976a9142f1b6a429396647d29cfc7254422e0e16740810788ac30a99e00000000001976a914689eea5c9eb3c296af083cb1c7dbdfce0386d11388ac00000000');

var insight = new explorers.Insight();
insight.broadcast(tx, function(err, txid) {
  if (err != null) {
    window.console.log('Broadcast Error:', err);
  } else {
    window.console.log('txid:', txid);
  }
});
</script>
</body></html>
```

**Comment by dskloet** [comment]
I thought `new Insight()` was testnet by default.
I changed it to `new Insight('https://test-insight.bitpay.com', 'testnet');` and now it says `Unexpected token T`.
I figured out that it is because it's trying to parse an error message as if it is a successful response.
The error message is `Transaction rejected by network (code -26). Reason: 64: non-canonical`. What does this mean?

**Comment by eordano** [comment]
Looks like some inputs are missing signatures. Take a look at the "script" fields, they are empty:

After doing:

```javascript
var bitcore = require('bitcore');
bitcore.Transaction('0100000004675f813a8a3bdfcfefc76db024b3c31b41fdec0e8c44cdac5d933b067ae3a045000000006a473044022072c9f556d7116157b208c6774f7f2f0698a29c567c1d82ba0e4b27d31af5bc8c022033a340c0f051ca72bd9fbce8b9156d2ef6e280cf05bce5bfe05ce840ebf7f4bf01210364ca17e9a443f775d3a26cd8e4f4873c7186c481fb741ec5e66b1c9b8571b3c8ffffffff185f22601506eda04d65643a94cb0f1d6ff0350a9c75950d1f80f48f157f0eab0000000000ffffffff9a14bd3b132e84408ded7a2a96f1fa76ed3ec03900673b87abe53161aa3cacfa0000000000ffffffff6928d19b1e902207fb4c8707a7af3ad4c97c70f7c4041255a9682427807392e70100000000ffffffff0280969800000000001976a9142f1b6a429396647d29cfc7254422e0e16740810788ac30a99e00000000001976a914689eea5c9eb3c296af083cb1c7dbdfce0386d11388ac00000000').toJSON();```

I'm getting:
```json
{
  "version": 1,
  "inputs": [
    {
      "prevTxId": "45a0e37a063b935daccd448c0eecfd411bc3b324b06dc7efcfdf3b8a3a815f67",
      "outputIndex": 0,
      "sequenceNumber": 4294967295,
      "script": "71 0x3044022072c9f556d7116157b208c6774f7f2f0698a29c567c1d82ba0e4b27d31af5bc8c022033a340c0f051ca72bd9fbce8b9156d2ef6e280cf05bce5bfe05ce840ebf7f4bf01 33 0x0364ca17e9a443f775d3a26cd8e4f4873c7186c481fb741ec5e66b1c9b8571b3c8"
    },
    {
      "prevTxId": "ab0e7f158ff4801f0d95759c0a35f06f1d0fcb943a64654da0ed061560225f18",
      "outputIndex": 0,
      "sequenceNumber": 4294967295,
      "script": ""
    },
    {
      "prevTxId": "faac3caa6131e5ab873b670039c03eed76faf1962a7aed8d40842e133bbd149a",
      "outputIndex": 0,
      "sequenceNumber": 4294967295,
      "script": ""
    },
    {
      "prevTxId": "e7927380272468a9551204c4f7707cc9d43aafa707874cfb0722901e9bd12869",
      "outputIndex": 1,
      "sequenceNumber": 4294967295,
      "script": ""
    }
  ],
  "outputs": [
    {
      "satoshis": 10000000,
      "script": "OP_DUP OP_HASH160 20 0x2f1b6a429396647d29cfc7254422e0e167408107 OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "satoshis": 10398000,
      "script": "OP_DUP OP_HASH160 20 0x689eea5c9eb3c296af083cb1c7dbdfce0386d113 OP_EQUALVERIFY OP_CHECKSIG"
    }
  ],
  "nLockTime": 0
}
```

**Comment by dskloet** [comment]
Thanks!
I had noticed the missing scripts but I had no idea what it meant.
Does script mean signature here?
I thought I only needed one signature because I'm only sending from one address, but I realize now that each output is signed rather than the entire transaction?

So it seems the main problem is not having clear error messages. I already filed the other bug about it trying to parse the error message but probably more can be done to make it clear and to do earlier checks?

**Comment by eordano** [comment]
Thanks for trying out the library. Your feedback helps us improve the API towards becoming the most usable library out there. I'll cross reference these current issues:

* [ ] https://github.com/bitpay/bitcore/issues/1049: Expose the method that does some checks used to know if a transaction looks all right
* [ ] https://github.com/bitpay/bitcore/issues/1060: Add more checks for common issues in a transaction
* [ ] https://github.com/bitpay/bitcore-explorers/issues/11: Validate that the transaction was fully signed before broadcasting

**Comment by dskloet** [comment]
It's fun to try it out and was pretty easy until I ran into this problem.
I made a simple web app to sign transactions offline.
I felt bad for bothering you with all my problems so I'm glad to hear you're happy with the feedback.

**Comment by maraoz** [comment]
@dskloet thanks a lot for finding this! we'll fix it shortly and report back

**Comment by braydonf** [comment]
Related? https://github.com/bitpay/bitcore-explorers/issues/20

**Comment by braydonf** [comment]
This is now reporting an error before broadcasting, as reported in https://github.com/bitpay/bitcore-explorers/issues/20
```
bitcore.ErrorTransactionInputMissingPreviousOutput: No previous output information.
```

**Comment by braydonf** [comment]
Instantiating an instance of Transaction from a hexa serialized version is also causing other problems/confusion: https://github.com/bitpay/bitcore/issues/1199

**Comment by braydonf** [comment]
`transaction.serialize()` throws an error now if a transaction isn't fully signed, and this should be resolved.

**Comment by OliveIT** [comment]
I got this error when I was trying to sign with a wrong secret key.
