### ISSUE TITLE
Improve P2P Peer connection

### ISSUE THREAD

**Issue by yemel** [bitpay/bitcore#711]
Some points for improvement:

- [x] Convert all messages content into javascript/bitcore objects (currently many of them are exposed as raw buffers) (https://github.com/bitpay/bitcore-p2p/pull/31)
- [ ] ~~Allow Peer class work on the browser~~ - Moved to a separate issue here: https://github.com/bitpay/bitcore-p2p/issues/21
- [ ] ~~Implement filterload, filteradd, filterclear, merkleblock~~ (moved to: https://github.com/bitpay/bitcore/issues/1030)
- [x] Add Peer discovery
- [ ] ~~Remove `Buffers` dependency~~ (https://github.com/bitpay/bitcore-p2p/issues/32)
